version: '3.9'

services:
    scraper:
        build: .
        ports:
            - "8080:5000"

    postgres_db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
